### ISSUE TITLE
Error creating DNS record

### ISSUE THREAD

**Issue by pascalgn** [libdns/azure#3]
I am getting the following error in Caddy when trying to renew a TLS certificate in letsencrypt. From the stack it looks like it fails to create the DNS record in the zone:

```
2022/07/12 16:43:44 panic: certificate worker: runtime error: slice bounds out of range [:-10]
goroutine 53 [running]:
github.com/caddyserver/certmagic.(*jobManager).worker.func1()
	github.com/caddyserver/certmagic@v0.15.2/async.go:58 +0x65
panic({0x15e53a0, 0xc000211428})
	runtime/panic.go:1038 +0x215
github.com/libdns/azure.generateRecordSetName(...)
	github.com/libdns/azure@v0.1.0/client.go:153
github.com/libdns/azure.(*Provider).createOrUpdateRecord(0xc00007dd40, {0x19ab778, 0xc000115920}, {0xc000813120, 0x19}, {{0x0, 0x0}, {0x16989dc, 0x3}, {0xc000041c80, ...}, ...}, ...)
	github.com/libdns/azure@v0.1.0/client.go:137 +0x618
github.com/libdns/azure.(*Provider).createRecord(...)
	github.com/libdns/azure@v0.1.0/client.go:79
```

Full Caddy logs (not sure if helpful) can be found here: https://github.com/caddyserver/caddy/issues/4881

Any ideas? 🙏

**Comment by kurokobo** [comment]
@pascalgn 
Hi, thanks for filling this issue. I was just checking the issue you opened on caddyserver/caddy.

Since you seem to be using `v0.1.0` of `dns.providers.azure`, could you try to reproduce it with `v0.2.0`? Some codes around the panic is slightly modified in `v0.2.0`.

**Comment by mholt** [comment]
So just looking closer at the stack trace now that I'm not mobile, I notice that the panic is actually caused by a `recover()` in CertMagic, from a panic in azure. Just wanted to clarify. So there is apparently a bug in CertMagic, but only when handling a bug in DNS provider libs :upside_down_face: 

Thanks for looking at it @kurokobo !

**Comment by kurokobo** [comment]
@pascalgn 
Hi, any update on this?

**Comment by mholt** [comment]
Am looking at this for a client, and I also seem to think the panic is probably (?) fixed in v0.2.0. I will let you know if we also encounter a panic, but I would _guess_ this is fixed.

**Comment by kurokobo** [comment]
@mholt 
Thanks for your investigation. Agree, it seems to be a panic where to get the relative name from the FQDN and zone name via my (a bit dirty) code :P
The `0.2.0` use `libdns.RelativeName` to get relative name, so if there is no problem with `Caddyfile`, I think this issue is already solved.

I will wait for the response from the author, but if there is no response for another week or so, I will close this issue due to lack of activity.

**Comment by kurokobo** [comment]
Closing this issue due to lack of activity.

**Comment by pascalgn** [comment]
Sorry for the late reply, but I'm still getting the same error with the latest Caddy (2.5.2)

From the error, I see it still uses libdns azure 0.1.0?

```
panic: certificate worker: runtime error: slice bounds out of range [:-10]
goroutine 25 [running]:
github.com/caddyserver/certmagic.(*jobManager).worker.func1()
        github.com/caddyserver/certmagic@v0.16.1/async.go:58 +0x65
panic({0x1912a40, 0xc0000425e8})
        runtime/panic.go:838 +0x207
github.com/libdns/azure.generateRecordSetName(...)
        github.com/libdns/azure@v0.1.0/client.go:153
github.com/libdns/azure.(*Provider).createOrUpdateRecord(0xc0000c4540, {0x1d6d530, 0xc0001c3050}, {0xc0006ec300, 0x19}, {{0x0, 0x0}, {0x19e0adc, 0x3}, {0xc0002fa420, ...}, ...}, ...)
        github.com/libdns/azure@v0.1.0/client.go:137 +0x618
github.com/libdns/azure.(*Provider).createRecord(...)
        github.com/libdns/azure@v0.1.0/client.go:79
```

**Comment by pascalgn** [comment]
OK, sorry again, I didn't realize that the azure DNS is an external module

I changed our build to `xcaddy build --with github.com/caddy-dns/azure@v0.2.0` and everything is working fine now!

Thank you for your time! 💝

**Comment by kurokobo** [comment]
Sounds good, thanks for testing 0.2.0 and updating this issue 🎉
